In [2]:
x = [{'city':'seoul', 'temp':10.0},{'city':'Dubiai', 'temp':33.5},{'city':'LA','temp':20.0}]
x

[{'city': 'seoul', 'temp': 10.0},
 {'city': 'Dubiai', 'temp': 33.5},
 {'city': 'LA', 'temp': 20.0}]

In [4]:
from sklearn.feature_extraction import DictVectorizer
vec = DictVectorizer(sparse = False)
vec.fit_transform(x)

array([[ 0. ,  0. ,  1. , 10. ],
       [ 1. ,  0. ,  0. , 33.5],
       [ 0. ,  1. ,  0. , 20. ]])

In [5]:
text = {'떴다 떴다 비행기 날아라 날아라',
       '높이 높이 날아라 우리 비행기',
       '내가 만든 비행기 날아라 날아라',
       '멀리 멀리 날아라 우리 비행기'}
text

{'내가 만든 비행기 날아라 날아라',
 '높이 높이 날아라 우리 비행기',
 '떴다 떴다 비행기 날아라 날아라',
 '멀리 멀리 날아라 우리 비행기'}

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
vec2 = CountVectorizer() #defult는 sparse = True
t = vec2.fit_transform(text).toarray() #toarray로 sparse 압축 해제

import pandas as pd
t1 = pd.DataFrame(t, columns = vec2.get_feature_names())
t1

날아라  내가  높이  떴다  만든  멀리  비행기  우리
0    2   1   0   0   1   0    1   0
1    1   0   2   0   0   0    1   1
2    1   0   0   0   0   2    1   1
3    2   0   0   2   0   0    1   0

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid = TfidfVectorizer()
x2 = tfid.fit_transform(text).toarray()
x3 = pd.DataFrame(x2, columns = tfid.get_feature_names())
x3

날아라        내가       높이       떴다        만든       멀리       비행기        우리
0  0.569241  0.545415  0.00000  0.00000  0.545415  0.00000  0.284620  0.000000
1  0.229589  0.000000  0.87992  0.00000  0.000000  0.00000  0.229589  0.346869
2  0.229589  0.000000  0.00000  0.00000  0.000000  0.87992  0.229589  0.346869
3  0.450735  0.000000  0.00000  0.86374  0.000000  0.00000  0.225368  0.000000

In [2]:
# 결축 자료 대체
import numpy as np
x_miss = np.array([[1,2,3,None],[5,np.NAN,7,8],[None,10,11,12],[13,np.nan,15,16]])
x_miss

array([[1, 2, 3, None],
       [5, nan, 7, 8],
       [None, 10, 11, 12],
       [13, nan, 15, 16]], dtype=object)

In [7]:
from sklearn.preprocessing import Imputer
im = Imputer(strategy = 'mean') #meman = 평균, median = 중위수
im.fit_transform(x_miss) #열의 평균값으로 대체

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


array([[ 1.        ,  2.        ,  3.        , 12.        ],
       [ 5.        ,  6.        ,  7.        ,  8.        ],
       [ 6.33333333, 10.        , 11.        , 12.        ],
       [13.        ,  6.        , 15.        , 16.        ]])

In [12]:
#데이터 로드
import pandas as pd
df1 = pd.read_csv("train.csv", engine = 'python')
print(df1.shape)
type(df1)

(1017209, 9)


pandas.core.frame.DataFrame

In [13]:
df1.head()

Store  DayOfWeek        Date  Sales  Customers  Open  Promo StateHoliday  \
0      1          5  2015-07-31   5263        555     1      1            0   
1      2          5  2015-07-31   6064        625     1      1            0   
2      3          5  2015-07-31   8314        821     1      1            0   
3      4          5  2015-07-31  13995       1498     1      1            0   
4      5          5  2015-07-31   4822        559     1      1            0   

   SchoolHoliday  
0              1  
1              1  
2              1  
3              1  
4              1

In [14]:
df2 = pd.read_csv("store.csv", engine = 'python')
df2.shape

(1115, 10)

In [15]:
df2.head()

Store StoreType Assortment  CompetitionDistance  CompetitionOpenSinceMonth  \
0      1         c          a               1270.0                        9.0   
1      2         a          a                570.0                       11.0   
2      3         a          a              14130.0                       12.0   
3      4         c          c                620.0                        9.0   
4      5         a          a              29910.0                        4.0   

   CompetitionOpenSinceYear  Promo2  Promo2SinceWeek  Promo2SinceYear  \
0                    2008.0       0              NaN              NaN   
1                    2007.0       1             13.0           2010.0   
2                    2006.0       1             14.0           2011.0   
3                    2009.0       0              NaN              NaN   
4                    2015.0       0              NaN              NaN   

     PromoInterval  
0              NaN  
1  Jan,Apr,Jul,Oct  
2  Jan,Apr,Jul,Oct  
3              NaN  
4              NaN

In [16]:
#데이터 통합
df = pd.merge(df1, df2, on = 'Store')
df.shape

(1017209, 18)

In [18]:
df.dtypes #변수의 자료 타입 확인

Store                          int64
DayOfWeek                      int64
Date                          object
Sales                          int64
Customers                      int64
Open                           int64
Promo                          int64
StateHoliday                  object
SchoolHoliday                  int64
StoreType                     object
Assortment                    object
CompetitionDistance          float64
CompetitionOpenSinceMonth    float64
CompetitionOpenSinceYear     float64
Promo2                         int64
Promo2SinceWeek              float64
Promo2SinceYear              float64
PromoInterval                 object
dtype: object

In [28]:
from collections import Counter
from sklearn.datasets import make_classification
from imblearn.over_sampling import SMOTE, ADASYN

#make_classfication: 불균형 데이터 만들기
#200x2행렬
X, y = make_classification(n_classes = 3, weights =[0.03, 0.07, 0.9], n_features = 2, n_informative = 2, n_redundant = 0, 
                           n_clusters_per_class = 1, n_samples = 200, random_state = 10)

print('Original dataset shape %s' % Counter(y))

ModuleNotFoundError: No module named 'imblearn'

In [26]:
import matplotlib.pyplot as plt

plt.scatter(X[:, 0], X[:, 1], marker = 'o', c = y, #y(class)마다 색을 다르게
            s = 100, edgecolor = "k", linewidth = 1) #s: 크기, edgecolor: 경계선
plt.xlabel("$X_1$")
plt.ylabel("$X_2$")
plt.show()

NameError: name 'X' is not defined

In [29]:
sm = SMOTE(random_state = 42)
X_res, y_res = sm.fit_resample(X, y)
print('Resampled dataset shape %s' % Counter(y_res))

NameError: name 'SMOTE' is not defined

In [30]:
import matplotlib.pyplot as plt

plt.scatter(X_res[:, 0], X_res[:, 1], marker = 'o', c = y_res, 
            s = 100, edgecolor = "k", linewidth = 1)
plt.xlabel("$X_1$")
plt.ylabel("$X_2$")
plt.show()

NameError: name 'X_res' is not defined

In [31]:
ada = ADASYN(random_state = 0)
X_syn, y_syn = ada.fit_resample(X, y)
print('Resampled dataset shape from ADASYN %s' % Counter(y_syn))

NameError: name 'ADASYN' is not defined

In [32]:
import matplotlib.pyplot as plt

plt.scatter(X_syn[:, 0], X_syn[:, 1], marker = 'o', c = y_syn,
            s = 100, edgecolor = "k", linewidth = 1)
plt.xlabel("$X_1$")
plt.ylabel("$X_2$")
plt.show()

NameError: name 'X_syn' is not defined

In [34]:
from imblearn.under_sampling import NearMiss

undersample = NearMiss(version = 3, n_neighbors_ver3 = 3)

X_under, y_under = undersample.fit_resample(X, y)

ModuleNotFoundError: No module named 'imblearn'

In [35]:
import matplotlib.pyplot as plt

plt.scatter(X_under[:, 0], X_under[:, 1], marker = 'o', c = y_under,
            s = 100, edgecolor = "k", linewidth = 1)
plt.xlabel("$X_1$")
plt.ylabel("$X_2$")
plt.show()

NameError: name 'X_under' is not defined